apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoforge-app
  namespace: {{ .Values.namespace }}
  labels:
    app: autoforge-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: autoforge-app
  template:
    metadata:
      labels:
        app: autoforge-app
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: autoforge-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: autoforge-config
            - secretRef:
                name: autoforge-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
