apiVersion: v1
kind: Service
metadata:
  name: autoforge-clusterip
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: autoforge-app
  ports:
    - port: {{ .Values.service.clusterIPPort }}
      targetPort: {{ .Values.service.targetPort }}
