apiVersion: v1
kind: ConfigMap
metadata:
  name: autoforge-config
  namespace: dev
data:
  APP_ENV: "development"
  LOG_LEVEL: "debug"
  DB_HOST: "autoforge-dev.cxxxx.ap-south-1.rds.amazonaws.com"
  DB_PORT: "3306"
  FEATURE_NEW_UI: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autoforge-config
  namespace: prod
data:
  APP_ENV: "production"
  LOG_LEVEL: "warn"
  DB_HOST: "autoforge-prod.cxxxx.ap-south-1.rds.amazonaws.com"
  DB_PORT: "3306"
  FEATURE_NEW_UI: "false"
