namespace: dev

image:
  repository: <ACCOUNT_ID>.dkr.ecr.ap-south-1.amazonaws.com/autoforge
  tag: latest

replicaCount: 2

resources:
  requests:
    cpu: 150m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  minReplicas: 2
  maxReplicas: 6
  cpuTarget: 70
  memoryTarget: 75

config:
  APP_ENV: "development"
  LOG_LEVEL: "debug"
  FEATURE_NEW_UI: "true"

ingress:
  enabled: true
